#ifndef PHOTONCAMERA_EXPORT_AVIF_H
#define PHOTONCAMERA_EXPORT_AVIF_H

#include <stddef.h>
#include <stdint.h>

/*
    filename - full path to save
    width, height - dimension of the image
    pixels - RGB values (each value take 2 bytes)
      total size of the buffer must be width * height * 3 * 2 bytes
    exif - EXIF buffer to save (can be nullptr)
      only bytes starting from TIFF header are saved
      save_avif_to_file will search for the TIFF header and skip bytes before the header
      Input can be taken from Exiv2::Blob generated by Exiv2::ExifParser::encode
    exifSize - size of EXIF buffer
*/
bool save_avif_to_file(const char *filename, uint32_t width, uint32_t height, const uint16_t *pixels, const uint8_t *exif, size_t exifSize);

#endif // PHOTONCAMERA_EXPORT_AVIF_H
